# Upload backend to AWS ECS

name: Deploy Frontend to Amazon S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Build Angular Application
        run: |
          # Move to Angular frontend directory, install Angular, build Angular app
          cd angular-frontend
          npm install -g @angular/cli
          npm install
          ng build --configuration production

      - name: Copy to S3
        run: |
          cd angular-frontend
          aws s3 sync ./dist/swim-planner-frontend/browser s3://swim-set-static-angular-site
